### ISSUE TITLE
[1.12.2] Crash upon Startup.

### ISSUE THREAD

**Issue by aking4125** [ultramarine11/wireless-industry#3]
Hello,

After adding this mod to our modpack, we got the following crash: 
[crash-2021-10-14_19.41.37-client.txt](https://github.com/ultramarine11/wireless-industry/files/7349907/crash-2021-10-14_19.41.37-client.txt)

Removing this mod from the pack fixes this issue, any ideas?

**Comment by ultramarine11** [comment]
Hello.
I have fixed the problem. Try the newest version (1.1.1) from CurseForge

**Comment by ultramarine11** [comment]
> Hello,
> 
> After adding this mod to our modpack, we got the following crash: [crash-2021-10-14_19.41.37-client.txt](https://github.com/ultramarine11/wireless-industry/files/7349907/crash-2021-10-14_19.41.37-client.txt)
> 
> Removing this mod from the pack fixes this issue, any ideas?
